version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prismauser
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: e-avm
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: